<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class QrCodeSettingsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $qrSettings = [
            // QR Code nastavenia
            [
                'key' => 'qr_code_auto_generate',
                'value' => '1',
                'type' => 'boolean',
                'group' => 'qr_codes',
                'label' => 'Automatické generovanie QR kódov',
                'description' => 'Automaticky generovať QR kódy pri vytváraní nového majetku',
                'is_public' => false,
                'is_editable' => true,
                'validation_rules' => json_encode(['boolean']),
                'options' => null,
                'sort_order' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'qr_code_size',
                'value' => '200',
                'type' => 'select',
                'group' => 'qr_codes',
                'label' => 'Veľkosť QR kódu',
                'description' => 'Veľkosť QR kódu v pixeloch',
                'is_public' => false,
                'is_editable' => true,
                'validation_rules' => json_encode(['required', 'in:100,150,200,250,300']),
                'options' => json_encode([
                    '100' => 'Malý (100px)',
                    '150' => 'Stredný (150px)', 
                    '200' => 'Veľký (200px)',
                    '250' => 'Extra veľký (250px)',
                    '300' => 'Maximálny (300px)'
                ]),
                'sort_order' => 101,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'qr_code_format',
                'value' => 'png',
                'type' => 'select',
                'group' => 'qr_codes',
                'label' => 'Formát QR kódu',
                'description' => 'Formát súboru pre exportované QR kódy',
                'is_public' => false,
                'is_editable' => true,
                'validation_rules' => json_encode(['required', 'in:png,svg,jpg']),
                'options' => json_encode([
                    'png' => 'PNG (odporúčané)',
                    'svg' => 'SVG (vektorový)',
                    'jpg' => 'JPEG'
                ]),
                'sort_order' => 102,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'qr_code_error_correction',
                'value' => 'M',
                'type' => 'select',
                'group' => 'qr_codes',
                'label' => 'Úroveň korekcie chýb',
                'description' => 'Úroveň korekcie chýb QR kódu (vyššia = odolnejší voči poškodeniu)',
                'is_public' => false,
                'is_editable' => true,
                'validation_rules' => json_encode(['required', 'in:L,M,Q,H']),
                'options' => json_encode([
                    'L' => 'Nízka (7%)',
                    'M' => 'Stredná (15%)',
                    'Q' => 'Vysoká (25%)',
                    'H' => 'Najvyššia (30%)'
                ]),
                'sort_order' => 103,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'qr_code_include_text',
                'value' => '1',
                'type' => 'boolean',
                'group' => 'qr_codes',
                'label' => 'Zobraziť text pod QR kódom',
                'description' => 'Zobraziť inventárne číslo ako text pod QR kódom',
                'is_public' => false,
                'is_editable' => true,
                'validation_rules' => json_encode(['boolean']),
                'options' => null,
                'sort_order' => 104,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'qr_code_base_url',
                'value' => config('app.url', 'https://inv.css-vranov.sk'),
                'type' => 'url',
                'group' => 'qr_codes',
                'label' => 'Základná URL pre QR kódy',
                'description' => 'URL adresa ktorá sa pridá do QR kódu pre priamy prístup k majetku',
                'is_public' => false,
                'is_editable' => true,
                'validation_rules' => json_encode(['required', 'url']),
                'options' => null,
                'sort_order' => 105,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'qr_code_batch_size',
                'value' => '50',
                'type' => 'integer',
                'group' => 'qr_codes',
                'label' => 'Veľkosť dávky pre hromadné generovanie',
                'description' => 'Maximálny počet QR kódov generovaných naraz',
                'is_public' => false,
                'is_editable' => true,
                'validation_rules' => json_encode(['required', 'integer', 'min:1', 'max:100']),
                'options' => null,
                'sort_order' => 106,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'qr_code_foreground_color',
                'value' => '#000000',
                'type' => 'color',
                'group' => 'qr_codes',
                'label' => 'Farba QR kódu',
                'description' => 'Farba čiar QR kódu (hex kód)',
                'is_public' => false,
                'is_editable' => true,
                'validation_rules' => json_encode(['required', 'regex:/^#[0-9A-Fa-f]{6}$/']),
                'options' => null,
                'sort_order' => 107,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'qr_code_background_color',
                'value' => '#FFFFFF',
                'type' => 'color',
                'group' => 'qr_codes',
                'label' => 'Farba pozadia QR kódu',
                'description' => 'Farba pozadia QR kódu (hex kód)',
                'is_public' => false,
                'is_editable' => true,
                'validation_rules' => json_encode(['required', 'regex:/^#[0-9A-Fa-f]{6}$/']),
                'options' => null,
                'sort_order' => 108,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'qr_code_margin',
                'value' => '4',
                'type' => 'integer',
                'group' => 'qr_codes',
                'label' => 'Okraj QR kódu',
                'description' => 'Veľkosť okraja okolo QR kódu (v moduloch)',
                'is_public' => false,
                'is_editable' => true,
                'validation_rules' => json_encode(['required', 'integer', 'min:0', 'max:10']),
                'options' => null,
                'sort_order' => 109,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'qr_code_storage_path',
                'value' => 'qr-codes',
                'type' => 'string',
                'group' => 'qr_codes',
                'label' => 'Priečinok pre QR kódy',
                'description' => 'Relatívna cesta v storage/app/public kde sa ukladajú QR kódy',
                'is_public' => false,
                'is_editable' => true,
                'validation_rules' => json_encode(['required', 'string', 'max:255']),
                'options' => null,
                'sort_order' => 110,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'qr_code_print_template',
                'value' => 'standard',
                'type' => 'select',
                'group' => 'qr_codes',
                'label' => 'Šablóna pre tlač',
                'description' => 'Predvolená šablóna pre tlač QR kódov',
                'is_public' => false,
                'is_editable' => true,
                'validation_rules' => json_encode(['required', 'in:standard,compact,detailed']),
                'options' => json_encode([
                    'standard' => 'Štandardná (QR + inv. číslo)',
                    'compact' => 'Kompaktná (len QR kód)',
                    'detailed' => 'Detailná (QR + inv. číslo + názov)'
                ]),
                'sort_order' => 111,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'qr_code_auto_print',
                'value' => '0',
                'type' => 'boolean',
                'group' => 'qr_codes',
                'label' => 'Automatická tlač po vytvorení',
                'description' => 'Automaticky otvoriť dialóg tlače po vytvorení nového majetku',
                'is_public' => false,
                'is_editable' => true,
                'validation_rules' => json_encode(['boolean']),
                'options' => null,
                'sort_order' => 112,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        // Odstránenie existujúcich QR nastavení a vloženie nových
        DB::table('system_settings')->where('group', 'qr_codes')->delete();
        DB::table('system_settings')->insert($qrSettings);
    }
}